In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/home/noahprowell/galvanize/case-studies/regression-case-study/predict_auction_price/data/Train.csv')

/home/noahprowell/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (13,39,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [4]:
df.head()

SalesID  SalePrice  MachineID  ModelID  datasource  auctioneerID  YearMade  \
0  1139246      66000     999089     3157         121           3.0      2004   
1  1139248      57000     117657       77         121           3.0      1996   
2  1139249      10000     434808     7009         121           3.0      2001   
3  1139251      38500    1026470      332         121           3.0      2001   
4  1139253      11000    1057373    17311         121           3.0      2007   

   MachineHoursCurrentMeter UsageBand         saledate  ...  \
0                      68.0       Low  11/16/2006 0:00  ...   
1                    4640.0       Low   3/26/2004 0:00  ...   
2                    2838.0      High   2/26/2004 0:00  ...   
3                    3486.0      High   5/19/2011 0:00  ...   
4                     722.0    Medium   7/23/2009 0:00  ...   

  Undercarriage_Pad_Width Stick_Length Thumb Pattern_Changer Grouser_Type  \
0                     NaN          NaN   NaN             NaN          NaN   
1                     NaN          NaN   NaN             NaN          NaN   
2                     NaN          NaN   NaN             NaN          NaN   
3                     NaN          NaN   NaN             NaN          NaN   
4                     NaN          NaN   NaN             NaN          NaN   

  Backhoe_Mounting Blade_Type Travel_Controls Differential_Type  \
0              NaN        NaN             NaN          Standard   
1              NaN        NaN             NaN          Standard   
2              NaN        NaN             NaN               NaN   
3              NaN        NaN             NaN               NaN   
4              NaN        NaN             NaN               NaN   

  Steering_Controls  
0      Conventional  
1      Conventional  
2               NaN  
3               NaN  
4               NaN  

[5 rows x 53 columns]

In [5]:
df.describe()

SalesID      SalePrice     MachineID        ModelID  \
count  4.011250e+05  401125.000000  4.011250e+05  401125.000000   
mean   1.919713e+06   31099.712848  1.217903e+06    6889.702980   
std    9.090215e+05   23036.898502  4.409920e+05    6221.777842   
min    1.139246e+06    4750.000000  0.000000e+00      28.000000   
25%    1.418371e+06   14500.000000  1.088697e+06    3259.000000   
50%    1.639422e+06   24000.000000  1.279490e+06    4604.000000   
75%    2.242707e+06   40000.000000  1.468067e+06    8724.000000   
max    6.333342e+06  142000.000000  2.486330e+06   37198.000000   

          datasource   auctioneerID       YearMade  MachineHoursCurrentMeter  
count  401125.000000  380989.000000  401125.000000              1.427650e+05  
mean      134.665810       6.556040    1899.156901              3.457955e+03  
std         8.962237      16.976779     291.797469              2.759026e+04  
min       121.000000       0.000000    1000.000000              0.000000e+00  
25%       132.000000       1.000000    1985.000000              0.000000e+00  
50%       132.000000       2.000000    1995.000000              0.000000e+00  
75%       136.000000       4.000000    2000.000000              3.025000e+03  
max       172.000000      99.000000    2013.000000              2.483300e+06

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 53 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   SalesID                   401125 non-null  int64  
 1   SalePrice                 401125 non-null  int64  
 2   MachineID                 401125 non-null  int64  
 3   ModelID                   401125 non-null  int64  
 4   datasource                401125 non-null  int64  
 5   auctioneerID              380989 non-null  float64
 6   YearMade                  401125 non-null  int64  
 7   MachineHoursCurrentMeter  142765 non-null  float64
 8   UsageBand                 69639 non-null   object 
 9   saledate                  401125 non-null  object 
 10  fiModelDesc               401125 non-null  object 
 11  fiBaseModel               401125 non-null  object 
 12  fiSecondaryDesc           263934 non-null  object 
 13  fiModelSeries             56908 non-null   o

In [8]:
df['ProductGroup'].unique()

array(['WL', 'SSL', 'TEX', 'BL', 'TTT', 'MG'], dtype=object)

In [9]:
df['Drive_System'].unique()

array([nan, 'Four Wheel Drive', 'Two Wheel Drive', 'No',
       'All Wheel Drive'], dtype=object)

In [10]:
df['Transmission'].unique()

array([nan, 'Powershuttle', 'Standard', 'Powershift',
       'None or Unspecified', 'Hydrostatic', 'Autoshift', 'Direct Drive',
       'AutoShift'], dtype=object)

In [11]:
df['Turbocharged'].unique()

array([nan, 'None or Unspecified', 'Yes'], dtype=object)

In [20]:
len(df['fiModelDesc'].unique())

4999

In [24]:
df['Drive_System'].isna().sum()

296764

In [ ]:
def drop_column(df, column_name):
    df = df.drop('column_name')
    return df